apiVersion: apps/v1
kind: Deployment
metadata:
  name: triumph-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: triumph-tracker
  template:
    metadata:
      labels:
        run: triumph-tracker
        app: triumph-tracker
    spec:
      containers:      
      - name: triumph-tracker
        image: 'ghcr.io/hanzov69/triumph-tracker:latest'
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: bungie-api-key
              key: API_KEY
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      nodeSelector:
        type: powerful

---
apiVersion: v1
kind: Service
metadata:
  name: triumph-tracker
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: triumph-tracker
  type: LoadBalancer
  loadBalancerIP: 192.168.1.109
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: bungie-api-key
  labels:
    app: triumph-tracker
type: Opaque
stringData:
    API_KEY: "12345"